---
- name: set-up complete tomcat9 setup
  hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: setting up tomcat9 using include module
    include: "{{item}}"
    with_items:
    - tomcat1.yaml
    - set_users.yaml
    - replace_port.yaml
    - restart_service.yaml
    - check_url_response.yaml

