---
- name: install tomcat9 and tomcat9-admin
  apt:
   name: "{{item.a}}"
   state: "{{item.b}}"
   update_cache: "{{item.c}}"
  with_items:
  - { a: "{{tomcatpkg}}", b: "{{state}}", c: "{{updaterepo}}" } 
  - { a: "{{tomcatadmpkg}}", b: "{{stateadm}}", c: "{{updaterepoadm}}" }
