---
- name: install packages using looping concept
  hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: install tree git apache2
    apt:
     name: "{{item.name}}"
     state: "{{item.state}}"
     update_cache: "{{item.update_cache}}"
    with_items:
    - { name: tree, state: present, update_cache: yes }
    - { name: git, state: present, update_cache: no }
    - { name: apache2, state: present, update_cache: no }
    - { name: tomcat9, state: present, update_cache: no }

